### ISSUE TITLE
Error when adding a user to a team

### ISSUE THREAD

**Issue by guitrottier** [UIUCLibrary/teams#87]
Greetings,

Testing with the module, I get this error when I add a user to a team.

- Omeka S version : 3.1.0
- Teams version : v3.1.0-7
- no other module activated

Regards,

```
Doctrine\DBAL\Exception\NotNullConstraintViolationException
An exception occurred while executing 'INSERT INTO team_user (is_current, id, team_id, user_id, role_id) VALUES (?, ?, ?, ?, ?)' with params [null, null, 1, 1, 1]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null

Détails :

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:112
Stack trace:
#0 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(112): PDOStatement->execute(NULL)
#1 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(287): Doctrine\DBAL\Statement->execute()
#3 vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1122): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(420): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(376): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /modules/Teams/src/Controller/UpdateController.php(61): Doctrine\ORM\EntityManager->flush()
#7 /modules/Teams/src/Controller/UpdateController.php(411): Teams\Controller\UpdateController->addTeamUser(1, 1, 1)
#8 /vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Teams\Controller\UpdateController->teamUpdateAction()
#9 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#10 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#11 /vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#12 /vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#13 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#14 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#15 /vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#16 /index.php(21): Laminas\Mvc\Application->run()
#17 {main}

Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(114): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
#1 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(177): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
#2 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(287): Doctrine\DBAL\Statement->execute()
#3 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1122): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#4 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(420): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#5 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(376): Doctrine\ORM\UnitOfWork->commit(NULL)
#6 /modules/Teams/src/Controller/UpdateController.php(61): Doctrine\ORM\EntityManager->flush()
#7 /modules/Teams/src/Controller/UpdateController.php(411): Teams\Controller\UpdateController->addTeamUser(1, 1, 1)
#8 /vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Teams\Controller\UpdateController->teamUpdateAction()
#9 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#10 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#11 /vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#12 /vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#13 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#14 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#15 /vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#16 /index.php(21): Laminas\Mvc\Application->run()
#17 {main}

Next Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO team_user (is_current, id, team_id, user_id, role_id) VALUES (?, ?, ?, ?, ?)' with params [null, null, 1, 1, 1]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:125
Stack trace:
#0 /vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDO\Exception))
#1 /vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'An exception oc...')
#2 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2214): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\MySQL\Driver), Object(Doctrine\DBAL\Driver\PDO\Exception), 'INSERT INTO tea...', Array)
#3 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(183): Doctrine\DBAL\Connection->handleExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'INSERT INTO tea...', Array, Array)
#4 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(287): Doctrine\DBAL\Statement->execute()
#5 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1122): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#6 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(420): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#7 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(376): Doctrine\ORM\UnitOfWork->commit(NULL)
#8 /modules/Teams/src/Controller/UpdateController.php(61): Doctrine\ORM\EntityManager->flush()
#9 /modules/Teams/src/Controller/UpdateController.php(411): Teams\Controller\UpdateController->addTeamUser(1, 1, 1)
#10 /vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Teams\Controller\UpdateController->teamUpdateAction()
#11 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#12 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#13 /vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#14 /vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#15 /vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#16 /vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#17 /vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#18 /index.php(21): Laminas\Mvc\Application->run()
#19 {main}
```

**Comment by alexdryden** [comment]
Hi @guitrottier, thanks for the report! This is an issue that cropped up when rebuilding the install script for 3.1 where I neglected to include a manual fix that we had to apply to the auto-generated doctrine install script. I'll push a patch shortly.

**Comment by alexdryden** [comment]
If you are using git to manage your install, you can checkout the v3.1.0-8 tag to get the fix. Then, uninstall and reinstall the module. Or, if you don't want to bother with that and have access to the database, you can can run `ALTER TABLE team_user MODIFY COLUMN id INT NOT NULL auto_increment` to apply the relevant fix. However, v3.1.0-8 also includes the uninstall fix, so if you need to uninstall teams for any reason checkout/upload that version first.

If you are using the .zip files to manage your install ~you'll need to wait to get the update till tomorrow because Github is having issues saving the .zip file~ it is now available.

____
If anyone reading this has tried to uninstall Teams on v3.1.0 < patch 8 and have run into an issue uninstalling, use one of the following procedures:
1. If you have access to the database:
`DROP TABLE team_asset;`
`DROP TABLE team;`
`UPDATE module SET is_active = 0 where id = "Teams";`
2. If you can only install/uninstall directories:
Delete the copy of Teams in your modules directory and install the version from v3.1.0-8. Go to http:/<your-omeka-instal>/admin/module and click "Uninstall" again.

**Comment by guitrottier** [comment]
OK, tested and working, thank you very much!
